package com.jeremie;

public class PlusMoins extends BaseGame {


    private boolean find;
    private boolean[] equal;
    private boolean[] more;
    private boolean[] less;

    /**
     * @param nbCases size of the combination.
     * @param nbTry maximum try/turn to find combination.
     * @param devMode enable display combination when the game at started in dev mode.
     */
    public PlusMoins(int nbCases, int nbTry, boolean devMode) {
        super(nbCases, nbTry, devMode);
        this.find = false;
        this.equal = new boolean[nbCases];
        this.more = new boolean[nbCases];
        this.less = new boolean[nbCases];
    }



    /**
     *
     * @param yourAnswer
     * @param computerAnswer
     */
    /*
    private void randomNumbers(String yourAnswer, String ordiAnswer) { //revoir cette méthode
        for(int index = 0 ; index < nbCases; index++) {
            int bMin = Character.getNumericValue(ordiAnswer.charAt(index));
            int bMax = Character.getNumericValue(yourAnswer.charAt(index));
            int randomNumber = (int) (Math.random() * (bMax - bMin)) + bMin;
            System.out.println(randomNumber);
        }
    }*/

    /**
     * Start challenge mode, The user propose a secret combination that the computer have to find.
     */
    @Override
    public void challengeMode() {
        combinationRandom("moreLess", 1); 
        displaySolutionForDev(combination); // if mode dev then display solution
        do {
            myAnswer = proposition("human", combination, "moreLess");
            compareAndDisplayIndicatorsPlacement(myAnswer, combination);
            System.out.println("\n");
            find = result(combination, myAnswer);
            nbTry--;
        } while (!find && nbTry != 0);
    }

    /**
     * Start defense mode. The computer have to search a random combination generated by you.
     */
    @Override
    public void defenseMode() {
        choiceCombinationToComputer();
        combinationRandom("moreLess", 2); //génère nouvelle combinaison
        computerAnswer = String.valueOf(combination);
        while(!find && tentative <= nbTry) {
            proposition("human", computerAnswer, "defense");
            compareAndDisplayIndicatorsPlacement(computerAnswer, myCombinationThatComputerFind);
            find = result(myCombinationThatComputerFind, computerAnswer);
            comparePlacement(computerAnswer, myCombinationThatComputerFind);
            computerAnswer = computerReflexion(equal, more, less, myCombinationThatComputerFind, computerAnswer);
            tentative++;
        }
    }

    /**
     * Start duel mode. Switch between user and computer to search a random combination.
     */
    @Override
    public void duelMode() {
        int nombre = 0;
        int tentative = 1;

        combination = String.valueOf(combination);
        computerAnswer = String.valueOf(combination);
        displaySolutionForDev(combination);
        do {
            if (nombre % 2 == 0) {
                System.out.print("C'est à votre tour : ");
                myAnswer = sc.nextLine();
                System.out.print("Votre proposition : " + myAnswer + " -> réponse : ");
                compareAndDisplayIndicatorsPlacement(myAnswer, combination);
                if (myAnswer.contains(combination)) {
                    find = true;
                    System.out.print("\n" + "Bravo vous avez trouvé la bonne combinaison : " + myAnswer);
                }
            } else {
                System.out.println("C'est au tour de l'ordinateur ! ");
                if(tentative == 1) {
                    System.out.print("L'ordinateur propose : " + computerAnswer + " -> réponse : ");
                    compareAndDisplayIndicatorsPlacement(computerAnswer, combination);
                }
                comparePlacement(computerAnswer, combination);
                computerAnswer = computerReflexion(equal, more, less, combination, computerAnswer);
                if(tentative > 1){
                    System.out.print("L'ordinateur propose : " + computerAnswer + " -> réponse : ");
                    compareAndDisplayIndicatorsPlacement(computerAnswer, combination);
                }
                if (computerAnswer.contains(combination)) {
                    find = true;
                    System.out.print("\n" + "C'est l'ordi qui a trouvé la bonne combinaison : " + computerAnswer);
                }
                tentative++;
            }
            nombre++;
            System.out.println("\n");
        } while (!find);
    }


    /**
     * Comparison between answer and combination.
     * @param answer your answer or computer answer.
     * @param combination secret combination.
     */
    private void compareAndDisplayIndicatorsPlacement(String answer, String combination) {
        for (int i = 0; i < answer.length(); i++) {
            if (answer.charAt(i) == combination.charAt(i)) {
                System.out.print("=");
            } else if (answer.charAt(i) < combination.charAt(i)) {
                System.out.print("+");
            } else if (answer.charAt(i) > combination.charAt(i)) {
                System.out.print("-");
            }
        }
        System.out.println();
    }

    /**
     * Comparison between answer and combination.
     * @param answer your answer or computer answer.
     * @param combination secret combination.
     */
    private void comparePlacement(String answer, String combination) {
        for (int i = 0; i < answer.length(); i++) {
            if (answer.charAt(i) == combination.charAt(i)) {
                equal[i] = true;
            } else if (answer.charAt(i) < combination.charAt(i)) {
                more[i] = true;
            } else if (answer.charAt(i) > combination.charAt(i)) {
                less[i] = true;
            }
        }
    }


    /**
     * The computer is thinking about proposing an answer based on the indicators/
     * @param equal Array which catch with a boolean equal values between combination and answer
     * @param more  Array which catch with a boolean for greater number values between combination and answer
     * @param less  Array which catch with a boolean for smaller number values between combination and answer
     */

    public String computerReflexion(boolean[] equal, boolean[] more, boolean[] less, String yourResponseThatOrdiFind, String computerAnswer){
        char[] computerAnswers = new char[nbCases];
        String answer = "";
        for(int index = 0; index < nbCases; index++){
            computerAnswers[index] = computerAnswer.charAt(index);
        }
        for(int index = 0; index < nbCases; index++){
            int entier = 0;
            int newEntier = 0;
            if(equal[index] == true){
                computerAnswers[index] = yourResponseThatOrdiFind.charAt(index);
            }
            else if(more[index] == true){
                entier = Character.getNumericValue(computerAnswer.charAt(index));
                newEntier = entier + 1;
                computerAnswers[index] = Character.forDigit(newEntier,10);
            }
            else if(less[index] == true){
                entier = Character.getNumericValue(computerAnswer.charAt(index));
                newEntier = entier - 1;
                computerAnswers[index] = Character.forDigit(newEntier,10);
            }
            answer += computerAnswers[index];
        }
        return answer;
    }
}

