package com.jeremie;

import java.util.Scanner;

public class PlusMoinsGame implements GameMode {


    private int nbCases;
    private int nbTry;
    private Scanner sc;
    private boolean find;
    private boolean devMode;

    /**
     * @param nbCases size of the combination.
     * @param nbTry maximum try/turn to find combination.
     * @param devMode enable display combination when the game at started in dev mode.
     */
    public PlusMoinsGame(int nbCases, int nbTry, boolean devMode) {
        this.devMode = devMode;
        this.nbCases = nbCases;
        this.nbTry = nbTry;
        this.find = false;
        sc = new Scanner(System.in);
    }

    /**
     * Calculation of a random number.
     * @param nbCases size of the combination.
     * @return the random number.
     */
    private int randomNumberAndSelectedNumber(int nbCases) { //revoir cette méthode
        int bMin = (int) Math.pow(10, nbCases - 1);
        int bMax = (int) Math.pow(10, nbCases);
        int randomNumber = (int) (Math.random() * (bMax - bMin)) + bMin;
        return randomNumber;
    }

    /**
     * Start challenge mode, The user propose a secret combination that the computer have to find.
     */
    @Override
    public void challengeMode() {
        String myAnswer;
        String randomNumber;
        randomNumber = String.valueOf(randomNumberAndSelectedNumber(nbCases));
        displaySolutionForDev(randomNumber); // if mode dev then display solution
        System.out.print("Merci faire votre proposition : ");
        do {
            System.out.println();
            System.out.println("Il vous reste encore " + nbTry + " tentatives");
            myAnswer = sc.nextLine();
            System.out.print("Votre proposition : " + myAnswer + " -> réponse : ");
            compareAndDisplayPlacement(myAnswer, randomNumber);
            if (myAnswer.contains(randomNumber)) {
                find = true;
                System.out.print("\n" + "Bravo ! Vous avez trouvé la bonne combinaison : " + myAnswer);
            }
            nbTry--;
        } while (!find && nbTry != 0);
        if(!find){
            System.out.println();
            System.out.println("Malheureusement vous n'avez pas trouvé la bonne combinaison qui était :  " + randomNumber);
        }
    }

    /**
     * Start defense mode. The computer have to search a random combination generated by you.
     */
    @Override
    public void defenseMode() {
        String yourResponseThatOrdiFind;
        String ordiAnswer;
        int tentative = 1;
        System.out.print("Merci de choisir le nombre à 4 chiffres que l'ordinateur doit trouver : ");
        yourResponseThatOrdiFind = sc.nextLine();
        System.out.println("L'ordinateur doit retrouver la réponse suivante : " + yourResponseThatOrdiFind);
        while(!find && tentative <= nbTry){
            ordiAnswer = String.valueOf(randomNumberAndSelectedNumber(nbCases));
            System.out.print("Proposition " + tentative + " : " + ordiAnswer + " vérification des placements : ");
            compareAndDisplayPlacement(ordiAnswer, yourResponseThatOrdiFind);
            System.out.println();
            if (ordiAnswer.contains(yourResponseThatOrdiFind)) {
                find = true;
                System.out.print("\n" + "L'ordi a trouvé la bonne combinaison : " + ordiAnswer);
            }
            tentative++;
        }
        if(!find)
            System.out.print("\n" + "L'ordi n'a pas trouvé la bonne combinaison, qui est : " + yourResponseThatOrdiFind);
    }

    /**
     * Start duel mode. Switch between user and computer to search a random combination.
     */
    @Override
    public void duelMode() {
        int nombre = 0;
        String randomNumberAtFind;
        String myAnswer;
        String ordiAnswer;
        randomNumberAtFind = String.valueOf(randomNumberAndSelectedNumber(nbCases));
        displaySolutionForDev(randomNumberAtFind);
        do {
            if (nombre % 2 == 0) {
                System.out.print("C'est à votre tour : ");
                myAnswer = sc.nextLine();
                System.out.print("Votre réponse : " + myAnswer + " -> réponse : ");
                compareAndDisplayPlacement(myAnswer, randomNumberAtFind);
                if (myAnswer.contains(randomNumberAtFind)) {
                    find = true;
                    System.out.print("\n" + "Bravo vous avez trouvé la bonne combinaison : " + myAnswer);
                }
            } else {
                System.out.println("C'est au tour de l'ordinateur ! ");
                ordiAnswer = String.valueOf(randomNumberAndSelectedNumber(nbCases));
                System.out.print("L'ordinateur propose : " + ordiAnswer + " -> réponse : ");
                compareAndDisplayPlacement(ordiAnswer, randomNumberAtFind);
                if (ordiAnswer.contains(randomNumberAtFind)) {
                    find = true;
                    System.out.print("\n" + "C'est l'ordi qui a trouvé la bonne combinaison : " + ordiAnswer);
                }
            }
            nombre++;
            System.out.println("\n");
        } while (!find);
    }

    /**
     * Dislay the combination when the game at started in dev mode only.
     * @param combinaisonSecrète combination secret.
     */
    @Override
    public void displaySolutionForDev(String combinaisonSecrète) {
        if(devMode == true){
            System.out.println("Mode Développeur activé. Voici la combinaison secrète : " + combinaisonSecrète);
        }
    }

    /**
     * Compare la réponse à la combinaison et affiche des indications de placements +/-.
     * @param answer votre réponse ou celle de l'ordinateur selon le jeu.
     * @param combinaison la combinaison secrète
     */
    private void compareAndDisplayPlacement(String answer, String combinaison) {
        for (int i = 0; i < answer.length(); i++) {
            if (answer.charAt(i) == combinaison.charAt(i)) {
                System.out.print("=");
            } else if (answer.charAt(i) < combinaison.charAt(i)) {
                System.out.print("+");
            } else if (answer.charAt(i) > combinaison.charAt(i)) {
                System.out.print("-");
            }
        }
    }
}

