package com.jeremie;

import java.util.Arrays;
import java.util.Scanner;

public class PlusMoinsGame implements GameMode {


    private int nbCases;
    private int nbTry;
    private Scanner sc;
    private boolean find;
    private boolean devMode;
    private boolean[] equal;
    private boolean[] more;
    private boolean[] less;

    /**
     * @param nbCases size of the combination.
     * @param nbTry maximum try/turn to find combination.
     * @param devMode enable display combination when the game at started in dev mode.
     */
    public PlusMoinsGame(int nbCases, int nbTry, boolean devMode) {
        this.devMode = devMode;
        this.nbCases = nbCases;
        this.nbTry = nbTry;
        this.find = false;
        this.equal = new boolean[nbCases];
        this.more = new boolean[nbCases];
        this.less = new boolean[nbCases];
        sc = new Scanner(System.in);
    }

    /**
     * Calculation of a random number.
     * @return the random number.
     */
    private int randomNumberAndSelectedNumber() { //revoir cette méthode
        int bMin = (int) Math.pow(10, nbCases - 1);
        int bMax = (int) Math.pow(10, nbCases);
        int randomNumber = (int) (Math.random() * (bMax - bMin)) + bMin;
        return randomNumber;
    }


    /**
     *
     * @param yourAnswer
     * @param computerAnswer
     */
    /*
    private void randomNumbers(String yourAnswer, String ordiAnswer) { //revoir cette méthode
        for(int index = 0 ; index < nbCases; index++) {
            int bMin = Character.getNumericValue(ordiAnswer.charAt(index));
            int bMax = Character.getNumericValue(yourAnswer.charAt(index));
            int randomNumber = (int) (Math.random() * (bMax - bMin)) + bMin;
            System.out.println(randomNumber);
        }
    }*/

    /**
     * Start challenge mode, The user propose a secret combination that the computer have to find.
     */
    @Override
    public void challengeMode() {
        String myAnswer;
        String randomNumber;
        randomNumber = String.valueOf(randomNumberAndSelectedNumber());
        displaySolutionForDev(randomNumber); // if mode dev then display solution
        do {
            System.out.print("Merci faire votre proposition (");
            System.out.println("il vous reste encore " + (nbTry) + " tentatives) : ");
            myAnswer = sc.nextLine();
            System.out.print("Votre proposition : " + myAnswer + " -> réponse : ");
            compareAndDisplayPlacement(myAnswer, randomNumber);
            if (myAnswer.contains(randomNumber)) {
                find = true;
                System.out.print("\n" + "Bravo ! Vous avez trouvé la bonne combinaison : " + myAnswer);
            }
            nbTry--;
            System.out.println(" ");
        } while (!find && nbTry != 0);
        if(!find){
            System.out.println("Malheureusement vous n'avez pas trouvé la bonne combinaison qui était :  " + randomNumber);
        }
    }

    /**
     * Start defense mode. The computer have to search a random combination generated by you.
     */
    @Override
    public void defenseMode() {
        String yourResponseThatOrdiFind;
        String computerAnswer;
        int tentative = 1;
        System.out.print("Merci de choisir le nombre à 4 chiffres que l'ordinateur doit trouver : ");
        yourResponseThatOrdiFind = sc.nextLine();
        System.out.println("L'ordinateur doit retrouver la réponse suivante : " + yourResponseThatOrdiFind);
        computerAnswer = String.valueOf(randomNumberAndSelectedNumber());
        comparePlacement(computerAnswer, yourResponseThatOrdiFind);
        System.out.print("Proposition " + tentative + " : " + computerAnswer + " vérification des placements : ");
        while(!find && tentative <= nbTry){
            computerAnswer = computerReflexion(equal, more, less, yourResponseThatOrdiFind, computerAnswer);
            System.out.print("Proposition " + (tentative+1) + " : " + computerAnswer + " vérification des placements : ");
            compareAndDisplayPlacement(computerAnswer, yourResponseThatOrdiFind);
            comparePlacement(computerAnswer, yourResponseThatOrdiFind);
            System.out.println();
            if (computerAnswer.contains(yourResponseThatOrdiFind)) {
                find = true;
                System.out.print("\n" + "L'ordi a trouvé la bonne combinaison : " + computerAnswer);
            }
            tentative++;
        }
        if(!find)
            System.out.print("\n" + "L'ordi n'a pas trouvé la bonne combinaison, qui est : " + yourResponseThatOrdiFind);
    }

    /**
     * The computer is thinking about proposing an answer based on the indicators/
     * @param equal Array which catch with a boolean equal values between combination and answer
     * @param more  Array which catch with a boolean for greater number values between combination and answer
     * @param less  Array which catch with a boolean for smaller number values between combination and answer
     */

    public String computerReflexion(boolean[] equal, boolean[] more, boolean[] less, String yourResponseThatOrdiFind, String computerAnswer){
        char[] computerAnswers = new char[nbCases];
        String answer = "";
        for(int index = 0; index < nbCases; index++){
            computerAnswers[index] = computerAnswer.charAt(index);
        }
        for(int index = 0; index < nbCases; index++){
            int entier = 0;
            int newEntier = 0;
            if(equal[index] == true){
                computerAnswers[index] = yourResponseThatOrdiFind.charAt(index);
            }
            else if(more[index] == true){
                entier = Character.getNumericValue(computerAnswer.charAt(index));
                newEntier = entier + 1;
                computerAnswers[index] = Character.forDigit(newEntier,10);
            }
            else if(less[index] == true){
                entier = Character.getNumericValue(computerAnswer.charAt(index));
                newEntier = entier - 1;
                computerAnswers[index] = Character.forDigit(newEntier,10);
            }
            answer += computerAnswers[index];
        }
        return answer;
    }

    /**
     * Start duel mode. Switch between user and computer to search a random combination.
     */
    @Override
    public void duelMode() {
        int nombre = 0;
        int tentative = 1;
        String randomNumberAtFind;
        String myAnswer;
        String computerAnswer;

        randomNumberAtFind = String.valueOf(randomNumberAndSelectedNumber());
        computerAnswer = String.valueOf(randomNumberAndSelectedNumber());
        displaySolutionForDev(randomNumberAtFind);
        do {
            if (nombre % 2 == 0) {
                System.out.print("C'est à votre tour : ");
                myAnswer = sc.nextLine();
                System.out.print("Votre réponse : " + myAnswer + " -> réponse : ");
                compareAndDisplayPlacement(myAnswer, randomNumberAtFind);
                if (myAnswer.contains(randomNumberAtFind)) {
                    find = true;
                    System.out.print("\n" + "Bravo vous avez trouvé la bonne combinaison : " + myAnswer);
                }
            } else {
                System.out.println("C'est au tour de l'ordinateur ! ");
                if(tentative == 1) {
                    System.out.print("L'ordinateur propose : " + computerAnswer + " -> réponse : ");
                    compareAndDisplayPlacement(computerAnswer, randomNumberAtFind);
                }

                comparePlacement(computerAnswer, randomNumberAtFind);
                computerAnswer = computerReflexion(equal, more, less, randomNumberAtFind, computerAnswer);

                if(tentative > 1){
                    System.out.print("L'ordinateur propose : " + computerAnswer + " -> réponse : ");
                    compareAndDisplayPlacement(computerAnswer, randomNumberAtFind);
                }
                if (computerAnswer.contains(randomNumberAtFind)) {
                    find = true;
                    System.out.print("\n" + "C'est l'ordi qui a trouvé la bonne combinaison : " + computerAnswer);

                }
                tentative++;
            }
            nombre++;
            System.out.println("\n");
        } while (!find);
    }

    /**
     * Dislay the combination when the game at started in dev mode only.
     * @param combinaisonSecrète combination secret.
     */
    @Override
    public void displaySolutionForDev(String combinaisonSecrète) {
        if(devMode == true){
            System.out.println("Mode Développeur activé. Voici la combinaison secrète : " + combinaisonSecrète);
        }
    }

    /**
     * Comparison between answer and combination.
     * @param answer your answer or computer answer.
     * @param combination secret combination.
     */
    private void compareAndDisplayPlacement(String answer, String combination) {
        for (int i = 0; i < answer.length(); i++) {
            if (answer.charAt(i) == combination.charAt(i)) {
                System.out.print("=");
            } else if (answer.charAt(i) < combination.charAt(i)) {
                System.out.print("+");
            } else if (answer.charAt(i) > combination.charAt(i)) {
                System.out.print("-");
            }
        }
    }

    /**
     * Comparison between answer and combination.
     * @param answer your answer or computer answer.
     * @param combination secret combination.
     */
    private void comparePlacement(String answer, String combination) {
        for (int i = 0; i < answer.length(); i++) {
            if (answer.charAt(i) == combination.charAt(i)) {
                equal[i] = true;
            } else if (answer.charAt(i) < combination.charAt(i)) {
                more[i] = true;
            } else if (answer.charAt(i) > combination.charAt(i)) {
                less[i] = true;
            }
        }
    }
}

